// Generated by CoffeeScript 1.12.2
(function() {
  var Detector, JsCpd, Promise, Report, Strategy, debugPreprocessor, filesPreprocessor, logger, optionsPreprocessor;

  logger = require('winston');

  Detector = require('./detector').Detector;

  Strategy = require('./strategy').Strategy;

  Report = require('./report').Report;

  optionsPreprocessor = require('./preprocessors/options');

  filesPreprocessor = require('./preprocessors/files');

  debugPreprocessor = require('./preprocessors/debug');

  Promise = require("bluebird");

  JsCpd = (function() {
    function JsCpd() {}

    JsCpd.prototype.preProcessors = [optionsPreprocessor, filesPreprocessor, debugPreprocessor];

    JsCpd.prototype.LANGUAGES = [];

    JsCpd.prototype.execPreProcessors = function(list) {
      var i, len, preProcessor, results;
      results = [];
      for (i = 0, len = list.length; i < len; i++) {
        preProcessor = list[i];
        results.push(preProcessor(this));
      }
      return results;
    };

    JsCpd.prototype.run = function(options) {
      var clone, codeMap, detector, generateReport, report, strategy;
      this.options = options;
      this.execPreProcessors(this.preProcessors);
      if (!this.options.debug) {
        strategy = new Strategy(this.options);
        detector = new Detector(strategy);
        report = new Report(this.options);
        codeMap = detector.start(this.options.selectedFiles, this.options['min-lines'], this.options['min-tokens']);
        generateReport = (function(_this) {
          return function() {
            var reportResult;
            reportResult = report.generate(codeMap);
            _this.report = reportResult;
            _this.map = codeMap;
            return {
              report: _this.report,
              map: _this.map
            };
          };
        })(this);
        if (this.options.blame) {
          return Promise.all((function() {
            var i, len, ref, results;
            ref = codeMap.clones;
            results = [];
            for (i = 0, len = ref.length; i < len; i++) {
              clone = ref[i];
              results.push(clone.blame());
            }
            return results;
          })()).then(generateReport).error(generateReport);
        } else {
          return generateReport();
        }
      }
    };

    return JsCpd;

  })();

  module.exports = JsCpd;

}).call(this);
